/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thinkbigprojeto;


import javax.swing.JOptionPane;

/**
 *
 * @author abreu
 */
public class Criar extends javax.swing.JFrame {
    private Planta plantaCriada;
    private String nome;
    private String visualizacao;
    
    private Visualizacao v = new Visualizacao();
    
    public Planta getPlantaCriada() {
        return plantaCriada;
    }

    public void setPlantaCriada(Planta plantaCriada) {
        this.plantaCriada = plantaCriada;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getVisualizacao() {
        return visualizacao;
    }

    public void setVisualizacao(String visualizacao) {
        this.visualizacao = visualizacao;
    }
    
    /**
     * Creates new form Inicial
     */
    public Criar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputNomePlanta = new thinkbigprojeto.TextField();
        botaoPadrao1 = new thinkbigprojeto.botaoPadrao();
        inputVisualizacao = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        paisagem = new javax.swing.JLabel();
        retrato = new javax.swing.JLabel();
        quadrado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 72, 121));
        jLabel2.setText("Visualização");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 250, 110, 16);

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 72, 121));
        jLabel3.setText("Nome da Planta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 110, 16);

        inputNomePlanta.setBackground(new java.awt.Color(235, 239, 250));
        inputNomePlanta.setForeground(new java.awt.Color(51, 91, 218));
        inputNomePlanta.setToolTipText("");
        inputNomePlanta.setCaretColor(new java.awt.Color(51, 91, 218));
        inputNomePlanta.setDisabledTextColor(new java.awt.Color(51, 91, 218));
        inputNomePlanta.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        inputNomePlanta.setLabelText("");
        inputNomePlanta.setLineColor(new java.awt.Color(51, 91, 218));
        inputNomePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomePlantaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNomePlanta);
        inputNomePlanta.setBounds(40, 200, 410, 40);

        botaoPadrao1.setBackground(new java.awt.Color(56, 72, 121));
        botaoPadrao1.setForeground(new java.awt.Color(255, 255, 255));
        botaoPadrao1.setText("CRIAR NOVA PLANTA");
        botaoPadrao1.setToolTipText("");
        botaoPadrao1.setBorderColor(new java.awt.Color(56, 72, 121));
        botaoPadrao1.setColor(new java.awt.Color(56, 72, 121));
        botaoPadrao1.setColorClick(new java.awt.Color(56, 72, 121));
        botaoPadrao1.setColorOver(new java.awt.Color(39, 52, 89));
        botaoPadrao1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        botaoPadrao1.setRadius(7);
        botaoPadrao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPadrao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPadrao1);
        botaoPadrao1.setBounds(40, 480, 410, 30);

        inputVisualizacao.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        inputVisualizacao.setForeground(new java.awt.Color(56, 72, 121));
        inputVisualizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paisagem", "Retrato", "Quadrado" }));
        inputVisualizacao.setBorder(null);
        inputVisualizacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inputVisualizacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputVisualizacaoItemStateChanged(evt);
            }
        });
        inputVisualizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputVisualizacaoMouseClicked(evt);
            }
        });
        inputVisualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVisualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(inputVisualizacao);
        inputVisualizacao.setBounds(40, 270, 410, 40);

        jPanel1.setBackground(new java.awt.Color(235, 239, 250));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 310, 80, 40);

        jButton1.setBackground(new java.awt.Color(51, 92, 218));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/botao-voltar.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 570, 60, 26);

        paisagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/paisagem.png"))); // NOI18N
        getContentPane().add(paisagem);
        paisagem.setBounds(190, 340, 100, 100);

        retrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/retrato.png"))); // NOI18N
        getContentPane().add(retrato);
        retrato.setBounds(190, 340, 100, 100);

        quadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/quadrado.png"))); // NOI18N
        getContentPane().add(quadrado);
        quadrado.setBounds(190, 340, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/fundo-criar.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomePlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomePlantaActionPerformed

    private void inputVisualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVisualizacaoActionPerformed
        
    }//GEN-LAST:event_inputVisualizacaoActionPerformed

    private void botaoPadrao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPadrao1ActionPerformed
        this.nome = inputNomePlanta.getText();
        this.visualizacao = String.valueOf(inputVisualizacao.getSelectedItem());

        dispose();
        
        //criarPlanta(Jlist, nome, visualizacao);
    }//GEN-LAST:event_botaoPadrao1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputVisualizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputVisualizacaoMouseClicked

    }//GEN-LAST:event_inputVisualizacaoMouseClicked

    private void inputVisualizacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputVisualizacaoItemStateChanged

        switch(inputVisualizacao.getSelectedIndex()){
            case 0:
                v.trocarParaPaisagem();
                paisagem.setVisible(true);
                retrato.setVisible(false);
                quadrado.setVisible(false);
                break;
            case 1:
                v.trocarParaRetrato();
                paisagem.setVisible(false);
                retrato.setVisible(true);
                quadrado.setVisible(false);
                break;
            case 2: 
                v.trocarParaQuadrada();
                paisagem.setVisible(false);
                retrato.setVisible(false);
                quadrado.setVisible(true);
                break;
        }
        
    }//GEN-LAST:event_inputVisualizacaoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Criar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thinkbigprojeto.botaoPadrao botaoPadrao1;
    private thinkbigprojeto.TextField inputNomePlanta;
    private javax.swing.JComboBox<String> inputVisualizacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel paisagem;
    private javax.swing.JLabel quadrado;
    private javax.swing.JLabel retrato;
    // End of variables declaration//GEN-END:variables
}
