/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thinkbigprojeto;

import javax.swing.JOptionPane;
import jdk.jshell.spi.ExecutionControl;

/**
 *
 * @author abreu
 */
public class Entrar extends javax.swing.JFrame {
    Usuario user = new Usuario();
    /**
     * Creates new form Inicial
     */
     
        
    public Entrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputEmail = new thinkbigprojeto.TextField();
        botaoPadrao1 = new thinkbigprojeto.botaoPadrao();
        inputSenha = new thinkbigprojeto.PasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        inputEmail.setBackground(new java.awt.Color(51, 92, 218));
        inputEmail.setForeground(new java.awt.Color(255, 255, 255));
        inputEmail.setToolTipText("");
        inputEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputEmail.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        inputEmail.setLabelText("Email");
        inputEmail.setLineColor(new java.awt.Color(255, 255, 255));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        getContentPane().add(inputEmail);
        inputEmail.setBounds(670, 250, 300, 48);

        botaoPadrao1.setForeground(new java.awt.Color(51, 91, 218));
        botaoPadrao1.setText("ENTRAR");
        botaoPadrao1.setBorderColor(new java.awt.Color(51, 91, 218));
        botaoPadrao1.setColorClick(new java.awt.Color(153, 153, 153));
        botaoPadrao1.setColorOver(new java.awt.Color(204, 204, 204));
        botaoPadrao1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        botaoPadrao1.setRadius(7);
        botaoPadrao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPadrao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPadrao1);
        botaoPadrao1.setBounds(670, 400, 300, 30);

        inputSenha.setBackground(new java.awt.Color(51, 92, 213));
        inputSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputSenha.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        inputSenha.setLabelText("Senha");
        inputSenha.setLineColor(new java.awt.Color(255, 255, 255));
        inputSenha.setSelectionColor(new java.awt.Color(255, 255, 255));
        inputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(inputSenha);
        inputSenha.setBounds(670, 320, 300, 48);

        jButton2.setBackground(new java.awt.Color(51, 92, 218));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/botao-voltar.jpg"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1010, 550, 60, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/fundo-entrar.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void botaoPadrao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPadrao1ActionPerformed
        
        if((inputEmail.getText().equals("qwerty") && String.valueOf(inputSenha.getPassword()).equals("12345")) || 
                (inputEmail.getText().equals(user.login) && String.valueOf(inputSenha.getPassword()).equals(user.senha))){
            JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!");
            Criacoes cria = new Criacoes();
            cria.show();
            dispose();
        }else if(inputEmail.getText().equals("") || String.valueOf(inputSenha.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Algum dos campos ou os dois estão vazios!", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Email e/ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoPadrao1ActionPerformed

    private void inputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicial entrar = new Inicial();
        entrar.show();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thinkbigprojeto.botaoPadrao botaoPadrao1;
    private thinkbigprojeto.TextField inputEmail;
    private thinkbigprojeto.PasswordField inputSenha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
