/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thinkbigprojeto;

/**
 *
 * @author abreu
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoPadrao1 = new thinkbigprojeto.botaoPadrao();
        botaoPadrao2 = new thinkbigprojeto.botaoPadrao();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        botaoPadrao1.setBackground(new java.awt.Color(51, 91, 218));
        botaoPadrao1.setForeground(new java.awt.Color(255, 255, 255));
        botaoPadrao1.setText("ENTRAR");
        botaoPadrao1.setBorderColor(new java.awt.Color(51, 91, 218));
        botaoPadrao1.setColor(new java.awt.Color(51, 91, 218));
        botaoPadrao1.setColorClick(new java.awt.Color(39, 59, 120));
        botaoPadrao1.setColorOver(new java.awt.Color(47, 77, 173));
        botaoPadrao1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        botaoPadrao1.setRadius(7);
        botaoPadrao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPadrao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPadrao1);
        botaoPadrao1.setBounds(680, 530, 190, 60);

        botaoPadrao2.setForeground(new java.awt.Color(51, 91, 218));
        botaoPadrao2.setText("CADASTRAR");
        botaoPadrao2.setBorderColor(new java.awt.Color(51, 91, 218));
        botaoPadrao2.setColorClick(new java.awt.Color(204, 204, 255));
        botaoPadrao2.setColorOver(new java.awt.Color(231, 231, 231));
        botaoPadrao2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        botaoPadrao2.setRadius(7);
        botaoPadrao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPadrao2ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPadrao2);
        botaoPadrao2.setBounds(890, 530, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkbigprojeto/fundo-inicial.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPadrao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPadrao1ActionPerformed

        Entrar entrar = new Entrar();
        entrar.show();
        
        dispose();
    }//GEN-LAST:event_botaoPadrao1ActionPerformed

    private void botaoPadrao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPadrao2ActionPerformed
        Cadastrar cadastrar = new Cadastrar();
        cadastrar.show();
        
        dispose();
    }//GEN-LAST:event_botaoPadrao2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thinkbigprojeto.botaoPadrao botaoPadrao1;
    private thinkbigprojeto.botaoPadrao botaoPadrao2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
